version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
    - "8080:80"
    volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web-app
  web-app:
    build: .
    ports:
      - "8081:8080"

  redis-db:
    image: "redis:alpine"