version : '3.8'

services:
  nginx:
    image: nginx:latest
    ports: 
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-server
    
  api-server:
    build: .
    env_file:
      - ./.env
    depends_on: 
      - db
  db:
    image: postgres:15-alpine
    env_file:
      - ./.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: