name: Docker Image CI Test
# This is a test comment to trigger CI

on:
    push:
        branches: ["main"]
        paths:
            - "4.set_up_ci/**"

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./4.set_up_ci

        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "18"

            - name: Install dependencies
              run: npm install

            - name: .env Setting
              run: |
                  echo "POSTGRES_USER=${{secrets.POSTGRES_USER}}" >> .env
                  echo "POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}" >> .env
                  echo "POSTGRES_DB=${{secrets.POSTGRES_DB}}" >> .env

            - name: create Volume
              run: docker volume create docker_practice

            - name: Docker compose build
              run: docker compose up -d

            - name: Wait for services
              run: sleep 15

            - name: Run Unit & Integration Test
              run: npm test

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Stop services
              if: always()
              run: docker compose down

            - name: Build and push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: ./4.set_up_ci
                  file: ./4.set_up_ci/dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-repo:latest
