name: Docker Image CI/CD Test
# This is a test comment to trigger CI

on:
    push:
        branches: ["main"]
        paths:
            - "4./**"

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: ./4.

        steps:
            - name: Checkout source code
              uses: actions/checkout@v4

            - name: .env Setting
              run: |
                  echo "POSTGRES_USER=${{secrets.POSTGRES_USER}}" >> .env
                  echo "POSTGRES_PASSWORD=${{secrets.POSTGRES_PASSWORD}}" >> .env
                  echo "POSTGRES_DB=${{secrets.POSTGRES_DB}}" >> .env

            - name: create Volume
              run: docker volume create docker_practice

            - name: Docker compose build
              run: docker compose up -d

            - name: Run Unit & Integration Test
              run: npm test

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Stop services
              if: always()
              run: docker compose down

            - name: Build and push Docker Image
              uses: docker/build-push-action@v5
              with:
                  context: ./4.
                  file: ./4./dockerfile
                  push: true
                  tags: ${{ secrets.DOCKERHUB_USERNAME }}/my-repo:latest
